import { supabase } from './supabase';

export async function seedOpportunities() {
  const { data: categories } = await supabase.from('categories').select('*');
  if (!categories) return;

  const categoryMap = Object.fromEntries(categories.map(c => [c.name, c.id]));

  const today = new Date();
  const nextWeek = new Date(today);
  nextWeek.setDate(today.getDate() + 7);
  const nextMonth = new Date(today);
  nextMonth.setMonth(today.getMonth() + 1);

  const opportunities = [
    {
      title: 'Beach Cleanup - Coastal Conservation',
      description: 'Join us for a morning of coastal conservation! We\'ll clean up our local beaches, collect data on marine debris, and help protect sea turtle nesting sites. All materials provided, and we\'ll have refreshments afterward. Perfect for individuals, families, and groups.',
      organization: 'Ocean Guardians',
      category_id: categoryMap['Environmental'],
      location: 'Santa Monica, CA',
      is_remote: false,
      time_commitment: '3 hours',
      start_date: nextWeek.toISOString().split('T')[0],
      end_date: null,
      recurring: true,
      schedule: 'Every Saturday, 8:00 AM - 11:00 AM',
      spots_available: 30,
      spots_filled: 12,
      image_url: 'https://images.pexels.com/photos/2086361/pexels-photo-2086361.jpeg?auto=compress&cs=tinysrgb&w=800',
      impact_area: 'Environmental Conservation - Protecting marine ecosystems and reducing ocean pollution',
      requirements: 'Closed-toe shoes, sun protection. Minors must be accompanied by an adult.',
      active: true,
    },
    {
      title: 'After-School Math Tutoring',
      description: 'Help middle school students build confidence in mathematics! We\'re looking for volunteers to provide one-on-one or small group tutoring to students who need extra support. Make a lasting impact on a child\'s educational journey.',
      organization: 'Bright Futures Education',
      category_id: categoryMap['Education'],
      location: 'Oakland, CA',
      is_remote: false,
      time_commitment: '2 hours per week',
      start_date: today.toISOString().split('T')[0],
      end_date: nextMonth.toISOString().split('T')[0],
      recurring: true,
      schedule: 'Tuesdays or Thursdays, 3:30 PM - 5:30 PM',
      spots_available: 15,
      spots_filled: 8,
      image_url: 'https://images.pexels.com/photos/8500414/pexels-photo-8500414.jpeg?auto=compress&cs=tinysrgb&w=800',
      impact_area: 'Education - Improving academic outcomes for underserved youth',
      requirements: 'Background check required. Strong math skills (algebra level minimum).',
      active: true,
    },
    {
      title: 'Community Garden Volunteer',
      description: 'Get your hands dirty and help grow fresh produce for local food banks! Learn about sustainable agriculture, meet your neighbors, and contribute to food security in our community. No experience necessary - we\'ll teach you everything!',
      organization: 'Green Roots Community Farm',
      category_id: categoryMap['Environmental'],
      location: 'Portland, OR',
      is_remote: false,
      time_commitment: 'Flexible, 2-4 hours',
      start_date: today.toISOString().split('T')[0],
      end_date: null,
      recurring: true,
      schedule: 'Weekends, flexible morning or afternoon shifts',
      spots_available: 20,
      spots_filled: 5,
      image_url: 'https://images.pexels.com/photos/4503273/pexels-photo-4503273.jpeg?auto=compress&cs=tinysrgb&w=800',
      impact_area: 'Food Security & Environmental Sustainability',
      requirements: 'Comfortable working outdoors. Gloves and tools provided.',
      active: true,
    },
    {
      title: 'Senior Technology Help',
      description: 'Bridge the digital divide by helping seniors navigate technology! Teach basic computer skills, smartphone usage, video calling, and online safety. One-on-one sessions that make a real difference in combating senior isolation.',
      organization: 'SilverTech Connect',
      category_id: categoryMap['Senior Care'],
      location: 'San Diego, CA',
      is_remote: false,
      time_commitment: '1-2 hours per week',
      start_date: nextWeek.toISOString().split('T')[0],
      end_date: null,
      recurring: true,
      schedule: 'Flexible weekday hours, 10:00 AM - 4:00 PM',
      spots_available: 12,
      spots_filled: 3,
      image_url: 'https://images.pexels.com/photos/4058219/pexels-photo-4058219.jpeg?auto=compress&cs=tinysrgb&w=800',
      impact_area: 'Senior Wellbeing & Digital Inclusion',
      requirements: 'Patient, friendly demeanor. Basic tech proficiency required.',
      active: true,
    },
    {
      title: 'Animal Shelter Support',
      description: 'Help care for rescue animals waiting for their forever homes! Tasks include walking dogs, socializing cats, cleaning kennels, and assisting with adoption events. Build relationships with amazing animals while supporting their wellbeing.',
      organization: 'Second Chance Animal Rescue',
      category_id: categoryMap['Animals'],
      location: 'Austin, TX',
      is_remote: false,
      time_commitment: '3-4 hours per week',
      start_date: today.toISOString().split('T')[0],
      end_date: null,
      recurring: true,
      schedule: 'Flexible shifts available 7 days a week',
      spots_available: 25,
      spots_filled: 18,
      image_url: 'https://images.pexels.com/photos/4056535/pexels-photo-4056535.jpeg?auto=compress&cs=tinysrgb&w=800',
      impact_area: 'Animal Welfare - Reducing shelter stress and improving adoption rates',
      requirements: 'Must be 16+. Orientation required before first shift.',
      active: true,
    },
    {
      title: 'Remote Website Development for Nonprofits',
      description: 'Use your web development skills to help small nonprofits establish their online presence! Work remotely to build or improve websites, making it easier for organizations to reach donors and communicate their mission.',
      organization: 'Code for Good',
      category_id: categoryMap['Technology'],
      location: 'Remote',
      is_remote: true,
      time_commitment: '5-10 hours total',
      start_date: today.toISOString().split('T')[0],
      end_date: nextMonth.toISOString().split('T')[0],
      recurring: false,
      schedule: 'Flexible, work on your own schedule',
      spots_available: 8,
      spots_filled: 2,
      image_url: 'https://images.pexels.com/photos/1181467/pexels-photo-1181467.jpeg?auto=compress&cs=tinysrgb&w=800',
      impact_area: 'Nonprofit Technology & Digital Capacity Building',
      requirements: 'HTML/CSS/JavaScript skills. React or WordPress experience a plus.',
      active: true,
    },
    {
      title: 'Youth Soccer Coach Assistant',
      description: 'Help coach youth soccer for an underserved community! Support the head coach during practices and games, help with drills, and be a positive role model. Build kids\' confidence, teamwork skills, and love for the game.',
      organization: 'PlayForward Sports',
      category_id: categoryMap['Community'],
      location: 'Chicago, IL',
      is_remote: false,
      time_commitment: '4 hours per week',
      start_date: nextWeek.toISOString().split('T')[0],
      end_date: nextMonth.toISOString().split('T')[0],
      recurring: true,
      schedule: 'Wednesdays 5-7 PM (practice) and Saturdays 9-11 AM (games)',
      spots_available: 6,
      spots_filled: 4,
      image_url: 'https://images.pexels.com/photos/1618200/pexels-photo-1618200.jpeg?auto=compress&cs=tinysrgb&w=800',
      impact_area: 'Youth Development & Community Building',
      requirements: 'Basic soccer knowledge. Enthusiasm and reliability required. Background check needed.',
      active: true,
    },
    {
      title: 'Community Mural Project',
      description: 'Be part of creating a beautiful mural that represents our diverse community! Working alongside professional artists, volunteers will help with painting, design elements, and community engagement. No artistic experience required - just enthusiasm!',
      organization: 'Urban Canvas Collective',
      category_id: categoryMap['Arts & Culture'],
      location: 'Denver, CO',
      is_remote: false,
      time_commitment: '4-6 hours',
      start_date: nextWeek.toISOString().split('T')[0],
      end_date: nextWeek.toISOString().split('T')[0],
      recurring: false,
      schedule: 'Saturday, 10:00 AM - 4:00 PM',
      spots_available: 40,
      spots_filled: 15,
      image_url: 'https://images.pexels.com/photos/1579708/pexels-photo-1579708.jpeg?auto=compress&cs=tinysrgb&w=800',
      impact_area: 'Arts & Community Pride',
      requirements: 'Wear clothes that can get paint on them. All materials provided.',
      active: true,
    },
    {
      title: 'Food Bank Sorting & Distribution',
      description: 'Help fight hunger in our community by sorting donations and preparing food packages for families in need. Work alongside a great team in a warehouse setting to ensure food reaches those who need it most.',
      organization: 'Community Food Share',
      category_id: categoryMap['Community'],
      location: 'Seattle, WA',
      is_remote: false,
      time_commitment: '3 hours',
      start_date: today.toISOString().split('T')[0],
      end_date: null,
      recurring: true,
      schedule: 'Multiple shifts available: Weekday evenings or Saturday mornings',
      spots_available: 30,
      spots_filled: 22,
      image_url: 'https://images.pexels.com/photos/6646919/pexels-photo-6646919.jpeg?auto=compress&cs=tinysrgb&w=800',
      impact_area: 'Food Security - Serving 5,000+ families monthly',
      requirements: 'Ability to lift 25 lbs. Closed-toe shoes required.',
      active: true,
    },
    {
      title: 'Hospital Companion Volunteer',
      description: 'Provide comfort and companionship to patients during their hospital stay. Visit with patients, read to them, help with phone calls to family, or simply offer a friendly presence. Training provided.',
      organization: 'Healing Hearts Volunteers',
      category_id: categoryMap['Healthcare'],
      location: 'Boston, MA',
      is_remote: false,
      time_commitment: '4 hours per week',
      start_date: nextWeek.toISOString().split('T')[0],
      end_date: null,
      recurring: true,
      schedule: 'Flexible daytime hours, minimum 6-month commitment',
      spots_available: 10,
      spots_filled: 7,
      image_url: 'https://images.pexels.com/photos/8460157/pexels-photo-8460157.jpeg?auto=compress&cs=tinysrgb&w=800',
      impact_area: 'Patient Wellbeing & Healthcare Support',
      requirements: 'Background check, health screening, and training required. Must be 18+.',
      active: true,
    },
  ];

  const { error } = await supabase.from('opportunities').insert(opportunities);
  if (error) {
    console.error('Error seeding opportunities:', error);
  }
}
